// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage/v1/storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUploadURLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ObjectRef      string                 `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,5,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUploadURLRequest) Reset() {
	*x = CreateUploadURLRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadURLRequest) ProtoMessage() {}

func (x *CreateUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadURLRequest.ProtoReflect.Descriptor instead.
func (*CreateUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUploadURLRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateUploadURLRequest) GetObjectRef() string {
	if x != nil {
		return x.ObjectRef
	}
	return ""
}

func (x *CreateUploadURLRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CreateUploadURLRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateUploadURLRequest) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type ObjectExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ObjectRef     string                 `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectExistsRequest) Reset() {
	*x = ObjectExistsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectExistsRequest) ProtoMessage() {}

func (x *ObjectExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectExistsRequest.ProtoReflect.Descriptor instead.
func (*ObjectExistsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectExistsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ObjectExistsRequest) GetObjectRef() string {
	if x != nil {
		return x.ObjectRef
	}
	return ""
}

type ObjectExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectExistsResponse) Reset() {
	*x = ObjectExistsResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectExistsResponse) ProtoMessage() {}

func (x *ObjectExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectExistsResponse.ProtoReflect.Descriptor instead.
func (*ObjectExistsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type VerifyChecksumRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ObjectRef      string                 `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,3,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerifyChecksumRequest) Reset() {
	*x = VerifyChecksumRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChecksumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChecksumRequest) ProtoMessage() {}

func (x *VerifyChecksumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChecksumRequest.ProtoReflect.Descriptor instead.
func (*VerifyChecksumRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyChecksumRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VerifyChecksumRequest) GetObjectRef() string {
	if x != nil {
		return x.ObjectRef
	}
	return ""
}

func (x *VerifyChecksumRequest) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type VerifyChecksumResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       bool                   `protobuf:"varint,1,opt,name=matches,proto3" json:"matches,omitempty"`
	ActualSha256  string                 `protobuf:"bytes,2,opt,name=actual_sha256,json=actualSha256,proto3" json:"actual_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChecksumResponse) Reset() {
	*x = VerifyChecksumResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChecksumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChecksumResponse) ProtoMessage() {}

func (x *VerifyChecksumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChecksumResponse.ProtoReflect.Descriptor instead.
func (*VerifyChecksumResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyChecksumResponse) GetMatches() bool {
	if x != nil {
		return x.Matches
	}
	return false
}

func (x *VerifyChecksumResponse) GetActualSha256() string {
	if x != nil {
		return x.ActualSha256
	}
	return ""
}

type CreateDownloadURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ObjectRef     string                 `protobuf:"bytes,2,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	Requester     string                 `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDownloadURLRequest) Reset() {
	*x = CreateDownloadURLRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDownloadURLRequest) ProtoMessage() {}

func (x *CreateDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*CreateDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDownloadURLRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDownloadURLRequest) GetObjectRef() string {
	if x != nil {
		return x.ObjectRef
	}
	return ""
}

func (x *CreateDownloadURLRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

func (x *CreateDownloadURLRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type CreateUploadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUploadURLResponse) Reset() {
	*x = CreateUploadURLResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUploadURLResponse) ProtoMessage() {}

func (x *CreateUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUploadURLResponse.ProtoReflect.Descriptor instead.
func (*CreateUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUploadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateUploadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDownloadURLResponse) Reset() {
	*x = CreateDownloadURLResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDownloadURLResponse) ProtoMessage() {}

func (x *CreateDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*CreateDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *CreateDownloadURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateDownloadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\n" +
	"storage.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x01\n" +
	"\x16CreateUploadURLRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"object_ref\x18\x02 \x01(\tR\tobjectRef\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12'\n" +
	"\x0fchecksum_sha256\x18\x05 \x01(\tR\x0echecksumSha256\"Q\n" +
	"\x13ObjectExistsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"object_ref\x18\x02 \x01(\tR\tobjectRef\".\n" +
	"\x14ObjectExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"|\n" +
	"\x15VerifyChecksumRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"object_ref\x18\x02 \x01(\tR\tobjectRef\x12'\n" +
	"\x0fchecksum_sha256\x18\x03 \x01(\tR\x0echecksumSha256\"W\n" +
	"\x16VerifyChecksumResponse\x12\x18\n" +
	"\amatches\x18\x01 \x01(\bR\amatches\x12#\n" +
	"\ractual_sha256\x18\x02 \x01(\tR\factualSha256\"\xa1\x01\n" +
	"\x18CreateDownloadURLRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"object_ref\x18\x02 \x01(\tR\tobjectRef\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"f\n" +
	"\x17CreateUploadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"h\n" +
	"\x19CreateDownloadURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xfa\x02\n" +
	"\x0eStorageService\x12Z\n" +
	"\x0fCreateUploadURL\x12\".storage.v1.CreateUploadURLRequest\x1a#.storage.v1.CreateUploadURLResponse\x12Q\n" +
	"\fObjectExists\x12\x1f.storage.v1.ObjectExistsRequest\x1a .storage.v1.ObjectExistsResponse\x12W\n" +
	"\x0eVerifyChecksum\x12!.storage.v1.VerifyChecksumRequest\x1a\".storage.v1.VerifyChecksumResponse\x12`\n" +
	"\x11CreateDownloadURL\x12$.storage.v1.CreateDownloadURLRequest\x1a%.storage.v1.CreateDownloadURLResponseBCZAgithub.com/liangzai006/ani-model-service/api/storage/v1;storagev1b\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_storage_v1_storage_proto_goTypes = []any{
	(*CreateUploadURLRequest)(nil),    // 0: storage.v1.CreateUploadURLRequest
	(*ObjectExistsRequest)(nil),       // 1: storage.v1.ObjectExistsRequest
	(*ObjectExistsResponse)(nil),      // 2: storage.v1.ObjectExistsResponse
	(*VerifyChecksumRequest)(nil),     // 3: storage.v1.VerifyChecksumRequest
	(*VerifyChecksumResponse)(nil),    // 4: storage.v1.VerifyChecksumResponse
	(*CreateDownloadURLRequest)(nil),  // 5: storage.v1.CreateDownloadURLRequest
	(*CreateUploadURLResponse)(nil),   // 6: storage.v1.CreateUploadURLResponse
	(*CreateDownloadURLResponse)(nil), // 7: storage.v1.CreateDownloadURLResponse
	(*durationpb.Duration)(nil),       // 8: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	8, // 0: storage.v1.CreateDownloadURLRequest.ttl:type_name -> google.protobuf.Duration
	9, // 1: storage.v1.CreateUploadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	9, // 2: storage.v1.CreateDownloadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 3: storage.v1.StorageService.CreateUploadURL:input_type -> storage.v1.CreateUploadURLRequest
	1, // 4: storage.v1.StorageService.ObjectExists:input_type -> storage.v1.ObjectExistsRequest
	3, // 5: storage.v1.StorageService.VerifyChecksum:input_type -> storage.v1.VerifyChecksumRequest
	5, // 6: storage.v1.StorageService.CreateDownloadURL:input_type -> storage.v1.CreateDownloadURLRequest
	6, // 7: storage.v1.StorageService.CreateUploadURL:output_type -> storage.v1.CreateUploadURLResponse
	2, // 8: storage.v1.StorageService.ObjectExists:output_type -> storage.v1.ObjectExistsResponse
	4, // 9: storage.v1.StorageService.VerifyChecksum:output_type -> storage.v1.VerifyChecksumResponse
	7, // 10: storage.v1.StorageService.CreateDownloadURL:output_type -> storage.v1.CreateDownloadURLResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
