// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: storage/v1/storage.proto

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_CreateUploadURL_FullMethodName   = "/storage.v1.StorageService/CreateUploadURL"
	StorageService_ObjectExists_FullMethodName      = "/storage.v1.StorageService/ObjectExists"
	StorageService_VerifyChecksum_FullMethodName    = "/storage.v1.StorageService/VerifyChecksum"
	StorageService_CreateDownloadURL_FullMethodName = "/storage.v1.StorageService/CreateDownloadURL"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	CreateUploadURL(ctx context.Context, in *CreateUploadURLRequest, opts ...grpc.CallOption) (*CreateUploadURLResponse, error)
	ObjectExists(ctx context.Context, in *ObjectExistsRequest, opts ...grpc.CallOption) (*ObjectExistsResponse, error)
	VerifyChecksum(ctx context.Context, in *VerifyChecksumRequest, opts ...grpc.CallOption) (*VerifyChecksumResponse, error)
	CreateDownloadURL(ctx context.Context, in *CreateDownloadURLRequest, opts ...grpc.CallOption) (*CreateDownloadURLResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) CreateUploadURL(ctx context.Context, in *CreateUploadURLRequest, opts ...grpc.CallOption) (*CreateUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUploadURLResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ObjectExists(ctx context.Context, in *ObjectExistsRequest, opts ...grpc.CallOption) (*ObjectExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectExistsResponse)
	err := c.cc.Invoke(ctx, StorageService_ObjectExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) VerifyChecksum(ctx context.Context, in *VerifyChecksumRequest, opts ...grpc.CallOption) (*VerifyChecksumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyChecksumResponse)
	err := c.cc.Invoke(ctx, StorageService_VerifyChecksum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateDownloadURL(ctx context.Context, in *CreateDownloadURLRequest, opts ...grpc.CallOption) (*CreateDownloadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDownloadURLResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	CreateUploadURL(context.Context, *CreateUploadURLRequest) (*CreateUploadURLResponse, error)
	ObjectExists(context.Context, *ObjectExistsRequest) (*ObjectExistsResponse, error)
	VerifyChecksum(context.Context, *VerifyChecksumRequest) (*VerifyChecksumResponse, error)
	CreateDownloadURL(context.Context, *CreateDownloadURLRequest) (*CreateDownloadURLResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) CreateUploadURL(context.Context, *CreateUploadURLRequest) (*CreateUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUploadURL not implemented")
}
func (UnimplementedStorageServiceServer) ObjectExists(context.Context, *ObjectExistsRequest) (*ObjectExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObjectExists not implemented")
}
func (UnimplementedStorageServiceServer) VerifyChecksum(context.Context, *VerifyChecksumRequest) (*VerifyChecksumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyChecksum not implemented")
}
func (UnimplementedStorageServiceServer) CreateDownloadURL(context.Context, *CreateDownloadURLRequest) (*CreateDownloadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDownloadURL not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_CreateUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateUploadURL(ctx, req.(*CreateUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ObjectExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ObjectExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ObjectExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ObjectExists(ctx, req.(*ObjectExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_VerifyChecksum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyChecksumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).VerifyChecksum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_VerifyChecksum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).VerifyChecksum(ctx, req.(*VerifyChecksumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateDownloadURL(ctx, req.(*CreateDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUploadURL",
			Handler:    _StorageService_CreateUploadURL_Handler,
		},
		{
			MethodName: "ObjectExists",
			Handler:    _StorageService_ObjectExists_Handler,
		},
		{
			MethodName: "VerifyChecksum",
			Handler:    _StorageService_VerifyChecksum_Handler,
		},
		{
			MethodName: "CreateDownloadURL",
			Handler:    _StorageService_CreateDownloadURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage/v1/storage.proto",
}
