// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inference/v1/model_reference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckModelVersionReferencesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One to 256 actual ModelVersion UUIDs. Service/operation/model IDs are invalid selectors.
	ModelVersionIds []string `protobuf:"bytes,1,rep,name=model_version_ids,json=modelVersionIds,proto3" json:"model_version_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckModelVersionReferencesRequest) Reset() {
	*x = CheckModelVersionReferencesRequest{}
	mi := &file_inference_v1_model_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckModelVersionReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckModelVersionReferencesRequest) ProtoMessage() {}

func (x *CheckModelVersionReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_model_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckModelVersionReferencesRequest.ProtoReflect.Descriptor instead.
func (*CheckModelVersionReferencesRequest) Descriptor() ([]byte, []int) {
	return file_inference_v1_model_reference_proto_rawDescGZIP(), []int{0}
}

func (x *CheckModelVersionReferencesRequest) GetModelVersionIds() []string {
	if x != nil {
		return x.ModelVersionIds
	}
	return nil
}

type CheckModelVersionReferencesResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HasActiveReferences bool                   `protobuf:"varint,1,opt,name=has_active_references,json=hasActiveReferences,proto3" json:"has_active_references,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CheckModelVersionReferencesResponse) Reset() {
	*x = CheckModelVersionReferencesResponse{}
	mi := &file_inference_v1_model_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckModelVersionReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckModelVersionReferencesResponse) ProtoMessage() {}

func (x *CheckModelVersionReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_v1_model_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckModelVersionReferencesResponse.ProtoReflect.Descriptor instead.
func (*CheckModelVersionReferencesResponse) Descriptor() ([]byte, []int) {
	return file_inference_v1_model_reference_proto_rawDescGZIP(), []int{1}
}

func (x *CheckModelVersionReferencesResponse) GetHasActiveReferences() bool {
	if x != nil {
		return x.HasActiveReferences
	}
	return false
}

var File_inference_v1_model_reference_proto protoreflect.FileDescriptor

const file_inference_v1_model_reference_proto_rawDesc = "" +
	"\n" +
	"\"inference/v1/model_reference.proto\x12\finference.v1\"P\n" +
	"\"CheckModelVersionReferencesRequest\x12*\n" +
	"\x11model_version_ids\x18\x01 \x03(\tR\x0fmodelVersionIds\"Y\n" +
	"#CheckModelVersionReferencesResponse\x122\n" +
	"\x15has_active_references\x18\x01 \x01(\bR\x13hasActiveReferences2\x9c\x01\n" +
	"\x15ModelReferenceService\x12\x82\x01\n" +
	"\x1bCheckModelVersionReferences\x120.inference.v1.CheckModelVersionReferencesRequest\x1a1.inference.v1.CheckModelVersionReferencesResponseBGZEgithub.com/liangzai006/ani-model-service/api/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_v1_model_reference_proto_rawDescOnce sync.Once
	file_inference_v1_model_reference_proto_rawDescData []byte
)

func file_inference_v1_model_reference_proto_rawDescGZIP() []byte {
	file_inference_v1_model_reference_proto_rawDescOnce.Do(func() {
		file_inference_v1_model_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_v1_model_reference_proto_rawDesc), len(file_inference_v1_model_reference_proto_rawDesc)))
	})
	return file_inference_v1_model_reference_proto_rawDescData
}

var file_inference_v1_model_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inference_v1_model_reference_proto_goTypes = []any{
	(*CheckModelVersionReferencesRequest)(nil),  // 0: inference.v1.CheckModelVersionReferencesRequest
	(*CheckModelVersionReferencesResponse)(nil), // 1: inference.v1.CheckModelVersionReferencesResponse
}
var file_inference_v1_model_reference_proto_depIdxs = []int32{
	0, // 0: inference.v1.ModelReferenceService.CheckModelVersionReferences:input_type -> inference.v1.CheckModelVersionReferencesRequest
	1, // 1: inference.v1.ModelReferenceService.CheckModelVersionReferences:output_type -> inference.v1.CheckModelVersionReferencesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inference_v1_model_reference_proto_init() }
func file_inference_v1_model_reference_proto_init() {
	if File_inference_v1_model_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_v1_model_reference_proto_rawDesc), len(file_inference_v1_model_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_v1_model_reference_proto_goTypes,
		DependencyIndexes: file_inference_v1_model_reference_proto_depIdxs,
		MessageInfos:      file_inference_v1_model_reference_proto_msgTypes,
	}.Build()
	File_inference_v1_model_reference_proto = out.File
	file_inference_v1_model_reference_proto_goTypes = nil
	file_inference_v1_model_reference_proto_depIdxs = nil
}
