// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: inference/v1/model_reference.proto

package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModelReferenceService_CheckModelVersionReferences_FullMethodName = "/inference.v1.ModelReferenceService/CheckModelVersionReferences"
)

// ModelReferenceServiceClient is the client API for ModelReferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tenant identity is supplied by the authenticated transport, never this request.
type ModelReferenceServiceClient interface {
	CheckModelVersionReferences(ctx context.Context, in *CheckModelVersionReferencesRequest, opts ...grpc.CallOption) (*CheckModelVersionReferencesResponse, error)
}

type modelReferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModelReferenceServiceClient(cc grpc.ClientConnInterface) ModelReferenceServiceClient {
	return &modelReferenceServiceClient{cc}
}

func (c *modelReferenceServiceClient) CheckModelVersionReferences(ctx context.Context, in *CheckModelVersionReferencesRequest, opts ...grpc.CallOption) (*CheckModelVersionReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckModelVersionReferencesResponse)
	err := c.cc.Invoke(ctx, ModelReferenceService_CheckModelVersionReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelReferenceServiceServer is the server API for ModelReferenceService service.
// All implementations must embed UnimplementedModelReferenceServiceServer
// for forward compatibility.
//
// Tenant identity is supplied by the authenticated transport, never this request.
type ModelReferenceServiceServer interface {
	CheckModelVersionReferences(context.Context, *CheckModelVersionReferencesRequest) (*CheckModelVersionReferencesResponse, error)
	mustEmbedUnimplementedModelReferenceServiceServer()
}

// UnimplementedModelReferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelReferenceServiceServer struct{}

func (UnimplementedModelReferenceServiceServer) CheckModelVersionReferences(context.Context, *CheckModelVersionReferencesRequest) (*CheckModelVersionReferencesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckModelVersionReferences not implemented")
}
func (UnimplementedModelReferenceServiceServer) mustEmbedUnimplementedModelReferenceServiceServer() {}
func (UnimplementedModelReferenceServiceServer) testEmbeddedByValue()                               {}

// UnsafeModelReferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelReferenceServiceServer will
// result in compilation errors.
type UnsafeModelReferenceServiceServer interface {
	mustEmbedUnimplementedModelReferenceServiceServer()
}

func RegisterModelReferenceServiceServer(s grpc.ServiceRegistrar, srv ModelReferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedModelReferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelReferenceService_ServiceDesc, srv)
}

func _ModelReferenceService_CheckModelVersionReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckModelVersionReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelReferenceServiceServer).CheckModelVersionReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelReferenceService_CheckModelVersionReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelReferenceServiceServer).CheckModelVersionReferences(ctx, req.(*CheckModelVersionReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelReferenceService_ServiceDesc is the grpc.ServiceDesc for ModelReferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelReferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.v1.ModelReferenceService",
	HandlerType: (*ModelReferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckModelVersionReferences",
			Handler:    _ModelReferenceService_CheckModelVersionReferences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inference/v1/model_reference.proto",
}
