syntax = "proto3";

package model.v1;

option go_package = "github.com/liangzai006/ani-model-service/api/model/v1;modelv1";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
}

message Server {
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }

  message Admin {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }

  GRPC grpc = 1;
  Admin admin = 2;
  google.protobuf.Duration shutdown_timeout = 3;
}
