// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: model/v1/model.proto

package modelv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Model struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Id             string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Source         string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	SourceRepoId   string                 `protobuf:"bytes,7,opt,name=source_repo_id,json=sourceRepoId,proto3" json:"source_repo_id,omitempty"`
	Capabilities   []string               `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TotalSizeBytes int64                  `protobuf:"varint,11,opt,name=total_size_bytes,json=totalSizeBytes,proto3" json:"total_size_bytes,omitempty"`
	Versions       []*ModelVersion        `protobuf:"bytes,12,rep,name=versions,proto3" json:"versions,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ModelId        string                 `protobuf:"bytes,15,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_model_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Model) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Model) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Model) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Model) GetSourceRepoId() string {
	if x != nil {
		return x.SourceRepoId
	}
	return ""
}

func (x *Model) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Model) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Model) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Model) GetTotalSizeBytes() int64 {
	if x != nil {
		return x.TotalSizeBytes
	}
	return 0
}

func (x *Model) GetVersions() []*ModelVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *Model) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Model) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Model) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ModelVersion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ModelId        string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Format         string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	IsEncrypted    bool                   `protobuf:"varint,5,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptAlgo    string                 `protobuf:"bytes,6,opt,name=encrypt_algo,json=encryptAlgo,proto3" json:"encrypt_algo,omitempty"`
	EncryptHint    string                 `protobuf:"bytes,7,opt,name=encrypt_hint,json=encryptHint,proto3" json:"encrypt_hint,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,9,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	StoragePath    string                 `protobuf:"bytes,10,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status         string                 `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	EngineType     string                 `protobuf:"bytes,13,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	StartupCommand string                 `protobuf:"bytes,14,opt,name=startup_command,json=startupCommand,proto3" json:"startup_command,omitempty"`
	StartupArgs    []string               `protobuf:"bytes,15,rep,name=startup_args,json=startupArgs,proto3" json:"startup_args,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelVersion) Reset() {
	*x = ModelVersion{}
	mi := &file_model_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelVersion) ProtoMessage() {}

func (x *ModelVersion) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelVersion.ProtoReflect.Descriptor instead.
func (*ModelVersion) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *ModelVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelVersion) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ModelVersion) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ModelVersion) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *ModelVersion) GetEncryptAlgo() string {
	if x != nil {
		return x.EncryptAlgo
	}
	return ""
}

func (x *ModelVersion) GetEncryptHint() string {
	if x != nil {
		return x.EncryptHint
	}
	return ""
}

func (x *ModelVersion) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModelVersion) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *ModelVersion) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *ModelVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ModelVersion) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ModelVersion) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *ModelVersion) GetStartupCommand() string {
	if x != nil {
		return x.StartupCommand
	}
	return ""
}

func (x *ModelVersion) GetStartupArgs() []string {
	if x != nil {
		return x.StartupArgs
	}
	return nil
}

type ModelArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelArtifact) Reset() {
	*x = ModelArtifact{}
	mi := &file_model_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelArtifact) ProtoMessage() {}

func (x *ModelArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelArtifact.ProtoReflect.Descriptor instead.
func (*ModelArtifact) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *ModelArtifact) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelArtifact) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ModelArtifact) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ModelArtifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ModelArtifact) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type CreateModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities   []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ModelId        string                 `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateModelRequest) Reset() {
	*x = CreateModelRequest{}
	mi := &file_model_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelRequest) ProtoMessage() {}

func (x *CreateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelRequest.ProtoReflect.Descriptor instead.
func (*CreateModelRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *CreateModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateModelRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateModelRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateModelRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *CreateModelRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_model_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_model_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type DeleteModelVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelVersionId string                 `protobuf:"bytes,2,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteModelVersionRequest) Reset() {
	*x = DeleteModelVersionRequest{}
	mi := &file_model_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelVersionRequest) ProtoMessage() {}

func (x *DeleteModelVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelVersionRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelVersionRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteModelVersionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteModelVersionRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

type DeleteModelVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelVersionResponse) Reset() {
	*x = DeleteModelVersionResponse{}
	mi := &file_model_v1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelVersionResponse) ProtoMessage() {}

func (x *DeleteModelVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelVersionResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelVersionResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{7}
}

type GetModelVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelVersionId string                 `protobuf:"bytes,2,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	ModelId        string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetModelVersionRequest) Reset() {
	*x = GetModelVersionRequest{}
	mi := &file_model_v1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelVersionRequest) ProtoMessage() {}

func (x *GetModelVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelVersionRequest.ProtoReflect.Descriptor instead.
func (*GetModelVersionRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{8}
}

func (x *GetModelVersionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetModelVersionRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *GetModelVersionRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GetModelVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetModelVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Version       *ModelVersion          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelVersionResponse) Reset() {
	*x = GetModelVersionResponse{}
	mi := &file_model_v1_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelVersionResponse) ProtoMessage() {}

func (x *GetModelVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelVersionResponse.ProtoReflect.Descriptor instead.
func (*GetModelVersionResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{9}
}

func (x *GetModelVersionResponse) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *GetModelVersionResponse) GetVersion() *ModelVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

type CursorPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPageRequest) Reset() {
	*x = CursorPageRequest{}
	mi := &file_model_v1_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPageRequest) ProtoMessage() {}

func (x *CursorPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPageRequest.ProtoReflect.Descriptor instead.
func (*CursorPageRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{10}
}

func (x *CursorPageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CursorPageRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type CursorPageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextCursor    string                 `protobuf:"bytes,1,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorPageMeta) Reset() {
	*x = CursorPageMeta{}
	mi := &file_model_v1_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorPageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorPageMeta) ProtoMessage() {}

func (x *CursorPageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorPageMeta.ProtoReflect.Descriptor instead.
func (*CursorPageMeta) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{11}
}

func (x *CursorPageMeta) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *CursorPageMeta) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          *CursorPageRequest     `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Capability    string                 `protobuf:"bytes,6,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_model_v1_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{12}
}

func (x *ListModelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListModelsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListModelsRequest) GetPage() *CursorPageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListModelsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListModelsRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ListModelsRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	Meta          *CursorPageMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_model_v1_model_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{13}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetMeta() *CursorPageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListModelVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Page          *CursorPageRequest     `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelVersionsRequest) Reset() {
	*x = ListModelVersionsRequest{}
	mi := &file_model_v1_model_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelVersionsRequest) ProtoMessage() {}

func (x *ListModelVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListModelVersionsRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{14}
}

func (x *ListModelVersionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListModelVersionsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ListModelVersionsRequest) GetPage() *CursorPageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListModelVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*ModelVersion        `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	Meta          *CursorPageMeta        `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelVersionsResponse) Reset() {
	*x = ListModelVersionsResponse{}
	mi := &file_model_v1_model_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelVersionsResponse) ProtoMessage() {}

func (x *ListModelVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListModelVersionsResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{15}
}

func (x *ListModelVersionsResponse) GetVersions() []*ModelVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListModelVersionsResponse) GetMeta() *CursorPageMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type CreateModelVersionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId        string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Format         string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	StoragePath    string                 `protobuf:"bytes,5,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,6,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IsEncrypted    bool                   `protobuf:"varint,8,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptAlgo    string                 `protobuf:"bytes,9,opt,name=encrypt_algo,json=encryptAlgo,proto3" json:"encrypt_algo,omitempty"`
	EncryptHint    string                 `protobuf:"bytes,10,opt,name=encrypt_hint,json=encryptHint,proto3" json:"encrypt_hint,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,11,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	EngineType     string                 `protobuf:"bytes,12,opt,name=engine_type,json=engineType,proto3" json:"engine_type,omitempty"`
	StartupCommand string                 `protobuf:"bytes,13,opt,name=startup_command,json=startupCommand,proto3" json:"startup_command,omitempty"`
	StartupArgs    []string               `protobuf:"bytes,14,rep,name=startup_args,json=startupArgs,proto3" json:"startup_args,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateModelVersionRequest) Reset() {
	*x = CreateModelVersionRequest{}
	mi := &file_model_v1_model_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateModelVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateModelVersionRequest) ProtoMessage() {}

func (x *CreateModelVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateModelVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateModelVersionRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{16}
}

func (x *CreateModelVersionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateModelVersionRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *CreateModelVersionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CreateModelVersionRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateModelVersionRequest) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *CreateModelVersionRequest) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

func (x *CreateModelVersionRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateModelVersionRequest) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *CreateModelVersionRequest) GetEncryptAlgo() string {
	if x != nil {
		return x.EncryptAlgo
	}
	return ""
}

func (x *CreateModelVersionRequest) GetEncryptHint() string {
	if x != nil {
		return x.EncryptHint
	}
	return ""
}

func (x *CreateModelVersionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateModelVersionRequest) GetEngineType() string {
	if x != nil {
		return x.EngineType
	}
	return ""
}

func (x *CreateModelVersionRequest) GetStartupCommand() string {
	if x != nil {
		return x.StartupCommand
	}
	return ""
}

func (x *CreateModelVersionRequest) GetStartupArgs() []string {
	if x != nil {
		return x.StartupArgs
	}
	return nil
}

type GetUploadURLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelId        string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	FileName       string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ChecksumSha256 string                 `protobuf:"bytes,7,opt,name=checksum_sha256,json=checksumSha256,proto3" json:"checksum_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUploadURLRequest) Reset() {
	*x = GetUploadURLRequest{}
	mi := &file_model_v1_model_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLRequest) ProtoMessage() {}

func (x *GetUploadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLRequest.ProtoReflect.Descriptor instead.
func (*GetUploadURLRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{17}
}

func (x *GetUploadURLRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetUploadURLRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GetUploadURLRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetUploadURLRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *GetUploadURLRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *GetUploadURLRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *GetUploadURLRequest) GetChecksumSha256() string {
	if x != nil {
		return x.ChecksumSha256
	}
	return ""
}

type GetUploadURLResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl      string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	StoragePath    string                 `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	DocId          string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UploadHeaders  map[string]string      `protobuf:"bytes,5,rep,name=upload_headers,json=uploadHeaders,proto3" json:"upload_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ModelVersionId string                 `protobuf:"bytes,6,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUploadURLResponse) Reset() {
	*x = GetUploadURLResponse{}
	mi := &file_model_v1_model_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadURLResponse) ProtoMessage() {}

func (x *GetUploadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadURLResponse.ProtoReflect.Descriptor instead.
func (*GetUploadURLResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{18}
}

func (x *GetUploadURLResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GetUploadURLResponse) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *GetUploadURLResponse) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *GetUploadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetUploadURLResponse) GetUploadHeaders() map[string]string {
	if x != nil {
		return x.UploadHeaders
	}
	return nil
}

func (x *GetUploadURLResponse) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

type ImportModelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Source         string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	RepoId         string                 `protobuf:"bytes,3,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	Revision       string                 `protobuf:"bytes,4,opt,name=revision,proto3" json:"revision,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	WebhookUrl     string                 `protobuf:"bytes,6,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	// Optional binding to an already-created model/version. Remote provider
	// imports may omit these until metadata resolution is complete.
	ModelId        string `protobuf:"bytes,7,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersionId string `protobuf:"bytes,8,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportModelRequest) Reset() {
	*x = ImportModelRequest{}
	mi := &file_model_v1_model_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportModelRequest) ProtoMessage() {}

func (x *ImportModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportModelRequest.ProtoReflect.Descriptor instead.
func (*ImportModelRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{19}
}

func (x *ImportModelRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImportModelRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ImportModelRequest) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *ImportModelRequest) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ImportModelRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ImportModelRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *ImportModelRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ImportModelRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

type ImportTask struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType       string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Status         string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LocationUrl    string                 `protobuf:"bytes,4,opt,name=location_url,json=locationUrl,proto3" json:"location_url,omitempty"`
	ModelId        string                 `protobuf:"bytes,5,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	ModelVersionId string                 `protobuf:"bytes,6,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	AttemptCount   int32                  `protobuf:"varint,7,opt,name=attempt_count,json=attemptCount,proto3" json:"attempt_count,omitempty"`
	ProgressPct    int32                  `protobuf:"varint,8,opt,name=progress_pct,json=progressPct,proto3" json:"progress_pct,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CompletedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ImportTask) Reset() {
	*x = ImportTask{}
	mi := &file_model_v1_model_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportTask) ProtoMessage() {}

func (x *ImportTask) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportTask.ProtoReflect.Descriptor instead.
func (*ImportTask) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{20}
}

func (x *ImportTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ImportTask) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ImportTask) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ImportTask) GetLocationUrl() string {
	if x != nil {
		return x.LocationUrl
	}
	return ""
}

func (x *ImportTask) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ImportTask) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *ImportTask) GetAttemptCount() int32 {
	if x != nil {
		return x.AttemptCount
	}
	return 0
}

func (x *ImportTask) GetProgressPct() int32 {
	if x != nil {
		return x.ProgressPct
	}
	return 0
}

func (x *ImportTask) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ImportTask) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ImportTask) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type GetImportTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportTaskRequest) Reset() {
	*x = GetImportTaskRequest{}
	mi := &file_model_v1_model_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportTaskRequest) ProtoMessage() {}

func (x *GetImportTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportTaskRequest.ProtoReflect.Descriptor instead.
func (*GetImportTaskRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{21}
}

func (x *GetImportTaskRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetImportTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type RetryImportTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryImportTaskRequest) Reset() {
	*x = RetryImportTaskRequest{}
	mi := &file_model_v1_model_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryImportTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryImportTaskRequest) ProtoMessage() {}

func (x *RetryImportTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryImportTaskRequest.ProtoReflect.Descriptor instead.
func (*RetryImportTaskRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{22}
}

func (x *RetryImportTaskRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RetryImportTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetImportTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *ImportTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportTaskResponse) Reset() {
	*x = GetImportTaskResponse{}
	mi := &file_model_v1_model_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportTaskResponse) ProtoMessage() {}

func (x *GetImportTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportTaskResponse.ProtoReflect.Descriptor instead.
func (*GetImportTaskResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{23}
}

func (x *GetImportTaskResponse) GetTask() *ImportTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type RetryImportTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *ImportTask            `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryImportTaskResponse) Reset() {
	*x = RetryImportTaskResponse{}
	mi := &file_model_v1_model_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryImportTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryImportTaskResponse) ProtoMessage() {}

func (x *RetryImportTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryImportTaskResponse.ProtoReflect.Descriptor instead.
func (*RetryImportTaskResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{24}
}

func (x *RetryImportTaskResponse) GetTask() *ImportTask {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetModelDownloadURLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ModelVersionId string                 `protobuf:"bytes,2,opt,name=model_version_id,json=modelVersionId,proto3" json:"model_version_id,omitempty"`
	Requester      string                 `protobuf:"bytes,3,opt,name=requester,proto3" json:"requester,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetModelDownloadURLRequest) Reset() {
	*x = GetModelDownloadURLRequest{}
	mi := &file_model_v1_model_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelDownloadURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelDownloadURLRequest) ProtoMessage() {}

func (x *GetModelDownloadURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelDownloadURLRequest.ProtoReflect.Descriptor instead.
func (*GetModelDownloadURLRequest) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{25}
}

func (x *GetModelDownloadURLRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetModelDownloadURLRequest) GetModelVersionId() string {
	if x != nil {
		return x.ModelVersionId
	}
	return ""
}

func (x *GetModelDownloadURLRequest) GetRequester() string {
	if x != nil {
		return x.Requester
	}
	return ""
}

type GetModelDownloadURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	StoragePath   string                 `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	IsEncrypted   bool                   `protobuf:"varint,3,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptAlgo   string                 `protobuf:"bytes,4,opt,name=encrypt_algo,json=encryptAlgo,proto3" json:"encrypt_algo,omitempty"`
	EncryptHint   string                 `protobuf:"bytes,5,opt,name=encrypt_hint,json=encryptHint,proto3" json:"encrypt_hint,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelDownloadURLResponse) Reset() {
	*x = GetModelDownloadURLResponse{}
	mi := &file_model_v1_model_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelDownloadURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelDownloadURLResponse) ProtoMessage() {}

func (x *GetModelDownloadURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_model_v1_model_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelDownloadURLResponse.ProtoReflect.Descriptor instead.
func (*GetModelDownloadURLResponse) Descriptor() ([]byte, []int) {
	return file_model_v1_model_proto_rawDescGZIP(), []int{26}
}

func (x *GetModelDownloadURLResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *GetModelDownloadURLResponse) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *GetModelDownloadURLResponse) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *GetModelDownloadURLResponse) GetEncryptAlgo() string {
	if x != nil {
		return x.EncryptAlgo
	}
	return ""
}

func (x *GetModelDownloadURLResponse) GetEncryptHint() string {
	if x != nil {
		return x.EncryptHint
	}
	return ""
}

func (x *GetModelDownloadURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_model_v1_model_proto protoreflect.FileDescriptor

const file_model_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x14model/v1/model.proto\x12\bmodel.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x04\n" +
	"\x05Model\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12$\n" +
	"\x0esource_repo_id\x18\a \x01(\tR\fsourceRepoId\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12(\n" +
	"\x10total_size_bytes\x18\v \x01(\x03R\x0etotalSizeBytes\x122\n" +
	"\bversions\x18\f \x03(\v2\x16.model.v1.ModelVersionR\bversions\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x19\n" +
	"\bmodel_id\x18\x0f \x01(\tR\amodelId\"\xff\x03\n" +
	"\fModelVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12!\n" +
	"\fis_encrypted\x18\x05 \x01(\bR\visEncrypted\x12!\n" +
	"\fencrypt_algo\x18\x06 \x01(\tR\vencryptAlgo\x12!\n" +
	"\fencrypt_hint\x18\a \x01(\tR\vencryptHint\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x03R\tsizeBytes\x12'\n" +
	"\x0fchecksum_sha256\x18\t \x01(\tR\x0echecksumSha256\x12!\n" +
	"\fstorage_path\x18\n" +
	" \x01(\tR\vstoragePath\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x12\x1f\n" +
	"\vengine_type\x18\r \x01(\tR\n" +
	"engineType\x12'\n" +
	"\x0fstartup_command\x18\x0e \x01(\tR\x0estartupCommand\x12!\n" +
	"\fstartup_args\x18\x0f \x03(\tR\vstartupArgs\"\x98\x01\n" +
	"\rModelArtifact\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06format\"\xf2\x01\n" +
	"\x12CreateModelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x19\n" +
	"\bmodel_id\x18\a \x01(\tR\amodelId\"I\n" +
	"\x0fGetModelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"L\n" +
	"\x12DeleteModelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"b\n" +
	"\x19DeleteModelVersionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12(\n" +
	"\x10model_version_id\x18\x02 \x01(\tR\x0emodelVersionId\"\x1c\n" +
	"\x1aDeleteModelVersionResponse\"\x94\x01\n" +
	"\x16GetModelVersionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12(\n" +
	"\x10model_version_id\x18\x02 \x01(\tR\x0emodelVersionId\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"r\n" +
	"\x17GetModelVersionResponse\x12%\n" +
	"\x05model\x18\x01 \x01(\v2\x0f.model.v1.ModelR\x05model\x120\n" +
	"\aversion\x18\x02 \x01(\v2\x16.model.v1.ModelVersionR\aversion\"A\n" +
	"\x11CursorPageRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"L\n" +
	"\x0eCursorPageMeta\x12\x1f\n" +
	"\vnext_cursor\x18\x01 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xcb\x01\n" +
	"\x11ListModelsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.model.v1.CursorPageRequestR\x04page\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"capability\x18\x06 \x01(\tR\n" +
	"capability\"k\n" +
	"\x12ListModelsResponse\x12'\n" +
	"\x06models\x18\x01 \x03(\v2\x0f.model.v1.ModelR\x06models\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.model.v1.CursorPageMetaR\x04meta\"\x83\x01\n" +
	"\x18ListModelVersionsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.model.v1.CursorPageRequestR\x04page\"}\n" +
	"\x19ListModelVersionsResponse\x122\n" +
	"\bversions\x18\x01 \x03(\v2\x16.model.v1.ModelVersionR\bversions\x12,\n" +
	"\x04meta\x18\x02 \x01(\v2\x18.model.v1.CursorPageMetaR\x04meta\"\xef\x03\n" +
	"\x19CreateModelVersionRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12!\n" +
	"\fstorage_path\x18\x05 \x01(\tR\vstoragePath\x12'\n" +
	"\x0fchecksum_sha256\x18\x06 \x01(\tR\x0echecksumSha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12!\n" +
	"\fis_encrypted\x18\b \x01(\bR\visEncrypted\x12!\n" +
	"\fencrypt_algo\x18\t \x01(\tR\vencryptAlgo\x12!\n" +
	"\fencrypt_hint\x18\n" +
	" \x01(\tR\vencryptHint\x12'\n" +
	"\x0fidempotency_key\x18\v \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\vengine_type\x18\f \x01(\tR\n" +
	"engineType\x12'\n" +
	"\x0fstartup_command\x18\r \x01(\tR\x0estartupCommand\x12!\n" +
	"\fstartup_args\x18\x0e \x03(\tR\vstartupArgs\"\xf5\x01\n" +
	"\x13GetUploadURLRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12'\n" +
	"\x0fchecksum_sha256\x18\a \x01(\tR\x0echecksumSha256\"\xf0\x02\n" +
	"\x14GetUploadURLResponse\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12!\n" +
	"\fstorage_path\x18\x02 \x01(\tR\vstoragePath\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12X\n" +
	"\x0eupload_headers\x18\x05 \x03(\v21.model.v1.GetUploadURLResponse.UploadHeadersEntryR\ruploadHeaders\x12(\n" +
	"\x10model_version_id\x18\x06 \x01(\tR\x0emodelVersionId\x1a@\n" +
	"\x12UploadHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x02\n" +
	"\x12ImportModelRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x17\n" +
	"\arepo_id\x18\x03 \x01(\tR\x06repoId\x12\x1a\n" +
	"\brevision\x18\x04 \x01(\tR\brevision\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\vwebhook_url\x18\x06 \x01(\tR\n" +
	"webhookUrl\x12\x19\n" +
	"\bmodel_id\x18\a \x01(\tR\amodelId\x12(\n" +
	"\x10model_version_id\x18\b \x01(\tR\x0emodelVersionId\"\xa9\x03\n" +
	"\n" +
	"ImportTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\flocation_url\x18\x04 \x01(\tR\vlocationUrl\x12\x19\n" +
	"\bmodel_id\x18\x05 \x01(\tR\amodelId\x12(\n" +
	"\x10model_version_id\x18\x06 \x01(\tR\x0emodelVersionId\x12#\n" +
	"\rattempt_count\x18\a \x01(\x05R\fattemptCount\x12!\n" +
	"\fprogress_pct\x18\b \x01(\x05R\vprogressPct\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12=\n" +
	"\fcompleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"L\n" +
	"\x14GetImportTaskRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"N\n" +
	"\x16RetryImportTaskRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\"A\n" +
	"\x15GetImportTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.model.v1.ImportTaskR\x04task\"C\n" +
	"\x17RetryImportTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.model.v1.ImportTaskR\x04task\"\x81\x01\n" +
	"\x1aGetModelDownloadURLRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12(\n" +
	"\x10model_version_id\x18\x02 \x01(\tR\x0emodelVersionId\x12\x1c\n" +
	"\trequester\x18\x03 \x01(\tR\trequester\"\x87\x02\n" +
	"\x1bGetModelDownloadURLResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12!\n" +
	"\fstorage_path\x18\x02 \x01(\tR\vstoragePath\x12!\n" +
	"\fis_encrypted\x18\x03 \x01(\bR\visEncrypted\x12!\n" +
	"\fencrypt_algo\x18\x04 \x01(\tR\vencryptAlgo\x12!\n" +
	"\fencrypt_hint\x18\x05 \x01(\tR\vencryptHint\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\x9c\b\n" +
	"\fModelService\x12<\n" +
	"\vCreateModel\x12\x1c.model.v1.CreateModelRequest\x1a\x0f.model.v1.Model\x126\n" +
	"\bGetModel\x12\x19.model.v1.GetModelRequest\x1a\x0f.model.v1.Model\x12G\n" +
	"\n" +
	"ListModels\x12\x1b.model.v1.ListModelsRequest\x1a\x1c.model.v1.ListModelsResponse\x12C\n" +
	"\vDeleteModel\x12\x1c.model.v1.DeleteModelRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\x0fGetModelVersion\x12 .model.v1.GetModelVersionRequest\x1a!.model.v1.GetModelVersionResponse\x12\\\n" +
	"\x11ListModelVersions\x12\".model.v1.ListModelVersionsRequest\x1a#.model.v1.ListModelVersionsResponse\x12_\n" +
	"\x12DeleteModelVersion\x12#.model.v1.DeleteModelVersionRequest\x1a$.model.v1.DeleteModelVersionResponse\x12Q\n" +
	"\x12CreateModelVersion\x12#.model.v1.CreateModelVersionRequest\x1a\x16.model.v1.ModelVersion\x12M\n" +
	"\fGetUploadURL\x12\x1d.model.v1.GetUploadURLRequest\x1a\x1e.model.v1.GetUploadURLResponse\x12A\n" +
	"\vImportModel\x12\x1c.model.v1.ImportModelRequest\x1a\x14.model.v1.ImportTask\x12P\n" +
	"\rGetImportTask\x12\x1e.model.v1.GetImportTaskRequest\x1a\x1f.model.v1.GetImportTaskResponse\x12V\n" +
	"\x0fRetryImportTask\x12 .model.v1.RetryImportTaskRequest\x1a!.model.v1.RetryImportTaskResponse\x12b\n" +
	"\x13GetModelDownloadURL\x12$.model.v1.GetModelDownloadURLRequest\x1a%.model.v1.GetModelDownloadURLResponseB?Z=github.com/liangzai006/ani-model-service/api/model/v1;modelv1b\x06proto3"

var (
	file_model_v1_model_proto_rawDescOnce sync.Once
	file_model_v1_model_proto_rawDescData []byte
)

func file_model_v1_model_proto_rawDescGZIP() []byte {
	file_model_v1_model_proto_rawDescOnce.Do(func() {
		file_model_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_model_v1_model_proto_rawDesc), len(file_model_v1_model_proto_rawDesc)))
	})
	return file_model_v1_model_proto_rawDescData
}

var file_model_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_model_v1_model_proto_goTypes = []any{
	(*Model)(nil),                       // 0: model.v1.Model
	(*ModelVersion)(nil),                // 1: model.v1.ModelVersion
	(*ModelArtifact)(nil),               // 2: model.v1.ModelArtifact
	(*CreateModelRequest)(nil),          // 3: model.v1.CreateModelRequest
	(*GetModelRequest)(nil),             // 4: model.v1.GetModelRequest
	(*DeleteModelRequest)(nil),          // 5: model.v1.DeleteModelRequest
	(*DeleteModelVersionRequest)(nil),   // 6: model.v1.DeleteModelVersionRequest
	(*DeleteModelVersionResponse)(nil),  // 7: model.v1.DeleteModelVersionResponse
	(*GetModelVersionRequest)(nil),      // 8: model.v1.GetModelVersionRequest
	(*GetModelVersionResponse)(nil),     // 9: model.v1.GetModelVersionResponse
	(*CursorPageRequest)(nil),           // 10: model.v1.CursorPageRequest
	(*CursorPageMeta)(nil),              // 11: model.v1.CursorPageMeta
	(*ListModelsRequest)(nil),           // 12: model.v1.ListModelsRequest
	(*ListModelsResponse)(nil),          // 13: model.v1.ListModelsResponse
	(*ListModelVersionsRequest)(nil),    // 14: model.v1.ListModelVersionsRequest
	(*ListModelVersionsResponse)(nil),   // 15: model.v1.ListModelVersionsResponse
	(*CreateModelVersionRequest)(nil),   // 16: model.v1.CreateModelVersionRequest
	(*GetUploadURLRequest)(nil),         // 17: model.v1.GetUploadURLRequest
	(*GetUploadURLResponse)(nil),        // 18: model.v1.GetUploadURLResponse
	(*ImportModelRequest)(nil),          // 19: model.v1.ImportModelRequest
	(*ImportTask)(nil),                  // 20: model.v1.ImportTask
	(*GetImportTaskRequest)(nil),        // 21: model.v1.GetImportTaskRequest
	(*RetryImportTaskRequest)(nil),      // 22: model.v1.RetryImportTaskRequest
	(*GetImportTaskResponse)(nil),       // 23: model.v1.GetImportTaskResponse
	(*RetryImportTaskResponse)(nil),     // 24: model.v1.RetryImportTaskResponse
	(*GetModelDownloadURLRequest)(nil),  // 25: model.v1.GetModelDownloadURLRequest
	(*GetModelDownloadURLResponse)(nil), // 26: model.v1.GetModelDownloadURLResponse
	nil,                                 // 27: model.v1.GetUploadURLResponse.UploadHeadersEntry
	(*timestamppb.Timestamp)(nil),       // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 29: google.protobuf.Empty
}
var file_model_v1_model_proto_depIdxs = []int32{
	1,  // 0: model.v1.Model.versions:type_name -> model.v1.ModelVersion
	28, // 1: model.v1.Model.created_at:type_name -> google.protobuf.Timestamp
	28, // 2: model.v1.Model.updated_at:type_name -> google.protobuf.Timestamp
	28, // 3: model.v1.ModelVersion.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: model.v1.GetModelVersionResponse.model:type_name -> model.v1.Model
	1,  // 5: model.v1.GetModelVersionResponse.version:type_name -> model.v1.ModelVersion
	10, // 6: model.v1.ListModelsRequest.page:type_name -> model.v1.CursorPageRequest
	0,  // 7: model.v1.ListModelsResponse.models:type_name -> model.v1.Model
	11, // 8: model.v1.ListModelsResponse.meta:type_name -> model.v1.CursorPageMeta
	10, // 9: model.v1.ListModelVersionsRequest.page:type_name -> model.v1.CursorPageRequest
	1,  // 10: model.v1.ListModelVersionsResponse.versions:type_name -> model.v1.ModelVersion
	11, // 11: model.v1.ListModelVersionsResponse.meta:type_name -> model.v1.CursorPageMeta
	28, // 12: model.v1.GetUploadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	27, // 13: model.v1.GetUploadURLResponse.upload_headers:type_name -> model.v1.GetUploadURLResponse.UploadHeadersEntry
	28, // 14: model.v1.ImportTask.created_at:type_name -> google.protobuf.Timestamp
	28, // 15: model.v1.ImportTask.completed_at:type_name -> google.protobuf.Timestamp
	20, // 16: model.v1.GetImportTaskResponse.task:type_name -> model.v1.ImportTask
	20, // 17: model.v1.RetryImportTaskResponse.task:type_name -> model.v1.ImportTask
	28, // 18: model.v1.GetModelDownloadURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 19: model.v1.ModelService.CreateModel:input_type -> model.v1.CreateModelRequest
	4,  // 20: model.v1.ModelService.GetModel:input_type -> model.v1.GetModelRequest
	12, // 21: model.v1.ModelService.ListModels:input_type -> model.v1.ListModelsRequest
	5,  // 22: model.v1.ModelService.DeleteModel:input_type -> model.v1.DeleteModelRequest
	8,  // 23: model.v1.ModelService.GetModelVersion:input_type -> model.v1.GetModelVersionRequest
	14, // 24: model.v1.ModelService.ListModelVersions:input_type -> model.v1.ListModelVersionsRequest
	6,  // 25: model.v1.ModelService.DeleteModelVersion:input_type -> model.v1.DeleteModelVersionRequest
	16, // 26: model.v1.ModelService.CreateModelVersion:input_type -> model.v1.CreateModelVersionRequest
	17, // 27: model.v1.ModelService.GetUploadURL:input_type -> model.v1.GetUploadURLRequest
	19, // 28: model.v1.ModelService.ImportModel:input_type -> model.v1.ImportModelRequest
	21, // 29: model.v1.ModelService.GetImportTask:input_type -> model.v1.GetImportTaskRequest
	22, // 30: model.v1.ModelService.RetryImportTask:input_type -> model.v1.RetryImportTaskRequest
	25, // 31: model.v1.ModelService.GetModelDownloadURL:input_type -> model.v1.GetModelDownloadURLRequest
	0,  // 32: model.v1.ModelService.CreateModel:output_type -> model.v1.Model
	0,  // 33: model.v1.ModelService.GetModel:output_type -> model.v1.Model
	13, // 34: model.v1.ModelService.ListModels:output_type -> model.v1.ListModelsResponse
	29, // 35: model.v1.ModelService.DeleteModel:output_type -> google.protobuf.Empty
	9,  // 36: model.v1.ModelService.GetModelVersion:output_type -> model.v1.GetModelVersionResponse
	15, // 37: model.v1.ModelService.ListModelVersions:output_type -> model.v1.ListModelVersionsResponse
	7,  // 38: model.v1.ModelService.DeleteModelVersion:output_type -> model.v1.DeleteModelVersionResponse
	1,  // 39: model.v1.ModelService.CreateModelVersion:output_type -> model.v1.ModelVersion
	18, // 40: model.v1.ModelService.GetUploadURL:output_type -> model.v1.GetUploadURLResponse
	20, // 41: model.v1.ModelService.ImportModel:output_type -> model.v1.ImportTask
	23, // 42: model.v1.ModelService.GetImportTask:output_type -> model.v1.GetImportTaskResponse
	24, // 43: model.v1.ModelService.RetryImportTask:output_type -> model.v1.RetryImportTaskResponse
	26, // 44: model.v1.ModelService.GetModelDownloadURL:output_type -> model.v1.GetModelDownloadURLResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_model_v1_model_proto_init() }
func file_model_v1_model_proto_init() {
	if File_model_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_model_v1_model_proto_rawDesc), len(file_model_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_v1_model_proto_goTypes,
		DependencyIndexes: file_model_v1_model_proto_depIdxs,
		MessageInfos:      file_model_v1_model_proto_msgTypes,
	}.Build()
	File_model_v1_model_proto = out.File
	file_model_v1_model_proto_goTypes = nil
	file_model_v1_model_proto_depIdxs = nil
}
