// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ID          pgtype.UUID        `json:"id"`
	Actor       string             `json:"actor"`
	Workload    string             `json:"workload"`
	RequestID   string             `json:"request_id"`
	TaskID      pgtype.UUID        `json:"task_id"`
	Action      string             `json:"action"`
	BeforeState string             `json:"before_state"`
	AfterState  string             `json:"after_state"`
	ErrorClass  string             `json:"error_class"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Model struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	DisplayName        string             `json:"display_name"`
	Description        string             `json:"description"`
	Source             string             `json:"source"`
	SourceRepoID       string             `json:"source_repo_id"`
	Capabilities       []byte             `json:"capabilities"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	TotalSizeBytes     int64              `json:"total_size_bytes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	ModelID            string             `json:"model_id"`
}

type ModelArtifact struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ID             pgtype.UUID        `json:"id"`
	ModelVersionID pgtype.UUID        `json:"model_version_id"`
	Provider       string             `json:"provider"`
	Reference      string             `json:"reference"`
	Format         string             `json:"format"`
	SizeBytes      int64              `json:"size_bytes"`
	Sha256         string             `json:"sha256"`
	IsEncrypted    bool               `json:"is_encrypted"`
	EncryptAlgo    string             `json:"encrypt_algo"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ModelImportTask struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            pgtype.UUID        `json:"model_id"`
	ModelVersionID     pgtype.UUID        `json:"model_version_id"`
	TaskType           string             `json:"task_type"`
	Source             string             `json:"source"`
	RepoID             string             `json:"repo_id"`
	Revision           string             `json:"revision"`
	IdempotencyKey     string             `json:"idempotency_key"`
	Status             string             `json:"status"`
	AttemptCount       int32              `json:"attempt_count"`
	ProgressPct        int32              `json:"progress_pct"`
	LeaseOwner         string             `json:"lease_owner"`
	LeaseEpoch         int64              `json:"lease_epoch"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	RequestFingerprint string             `json:"request_fingerprint"`
}

type ModelVersion struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            pgtype.UUID        `json:"model_id"`
	Version            string             `json:"version"`
	Format             string             `json:"format"`
	Status             string             `json:"status"`
	IsEncrypted        bool               `json:"is_encrypted"`
	EncryptAlgo        string             `json:"encrypt_algo"`
	EncryptHint        string             `json:"encrypt_hint"`
	SizeBytes          int64              `json:"size_bytes"`
	ChecksumSha256     string             `json:"checksum_sha256"`
	EngineType         string             `json:"engine_type"`
	StartupCommand     string             `json:"startup_command"`
	StartupArgs        []byte             `json:"startup_args"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
}
