// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindImportTask = `-- name: BindImportTask :execrows
UPDATE public.model_import_tasks
SET model_id = $5, model_version_id = $6, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status = 'importing'
  AND lease_owner = $3 AND lease_epoch = $4 AND lease_until > clock_timestamp()
  AND model_version_id IS NULL
`

type BindImportTaskParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ID             pgtype.UUID `json:"id"`
	LeaseOwner     string      `json:"lease_owner"`
	LeaseEpoch     int64       `json:"lease_epoch"`
	ModelID        pgtype.UUID `json:"model_id"`
	ModelVersionID pgtype.UUID `json:"model_version_id"`
}

func (q *Queries) BindImportTask(ctx context.Context, arg BindImportTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindImportTask,
		arg.TenantID,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseEpoch,
		arg.ModelID,
		arg.ModelVersionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimImportTask = `-- name: ClaimImportTask :one
UPDATE public.model_import_tasks
SET status = 'importing', lease_owner = $3, lease_epoch = lease_epoch + 1,
    lease_until = clock_timestamp() + ($4::bigint * interval '1 microsecond'),
    attempt_count = attempt_count + 1, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status IN ('pending','importing')
  AND next_attempt_at <= clock_timestamp()
  AND (lease_until IS NULL OR lease_until <= clock_timestamp())
RETURNING tenant_id, id, model_id, model_version_id, task_type, source, repo_id, revision, idempotency_key, status, attempt_count, progress_pct, lease_owner, lease_epoch, lease_until, next_attempt_at, error_message, created_at, updated_at, completed_at, request_fingerprint
`

type ClaimImportTaskParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ID         pgtype.UUID `json:"id"`
	LeaseOwner string      `json:"lease_owner"`
	Column4    int64       `json:"column_4"`
}

func (q *Queries) ClaimImportTask(ctx context.Context, arg ClaimImportTaskParams) (ModelImportTask, error) {
	row := q.db.QueryRow(ctx, claimImportTask,
		arg.TenantID,
		arg.ID,
		arg.LeaseOwner,
		arg.Column4,
	)
	var i ModelImportTask
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.ModelVersionID,
		&i.TaskType,
		&i.Source,
		&i.RepoID,
		&i.Revision,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.ProgressPct,
		&i.LeaseOwner,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestFingerprint,
	)
	return i, err
}

const completeImportTask = `-- name: CompleteImportTask :execrows
UPDATE public.model_import_tasks
SET status = 'completed', progress_pct = 100, lease_owner = '', lease_until = NULL,
    completed_at = clock_timestamp(), updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status = 'importing'
  AND lease_owner = $3 AND lease_epoch = $4 AND lease_until > clock_timestamp()
`

type CompleteImportTaskParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ID         pgtype.UUID `json:"id"`
	LeaseOwner string      `json:"lease_owner"`
	LeaseEpoch int64       `json:"lease_epoch"`
}

func (q *Queries) CompleteImportTask(ctx context.Context, arg CompleteImportTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeImportTask,
		arg.TenantID,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseEpoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createImportTask = `-- name: CreateImportTask :one
INSERT INTO public.model_import_tasks
 (tenant_id, id, model_id, model_version_id, task_type, source, repo_id,
  revision, idempotency_key, request_fingerprint, status)
VALUES ($1, $2, $3, NULLIF($4, '00000000-0000-0000-0000-000000000000')::uuid,
        $5, $6, $7, $8, $9, $10, 'pending')
RETURNING tenant_id, id, model_id, model_version_id, task_type, source, repo_id, revision, idempotency_key, status, attempt_count, progress_pct, lease_owner, lease_epoch, lease_until, next_attempt_at, error_message, created_at, updated_at, completed_at, request_fingerprint
`

type CreateImportTaskParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	ID                 pgtype.UUID `json:"id"`
	ModelID            pgtype.UUID `json:"model_id"`
	Column4            interface{} `json:"column_4"`
	TaskType           string      `json:"task_type"`
	Source             string      `json:"source"`
	RepoID             string      `json:"repo_id"`
	Revision           string      `json:"revision"`
	IdempotencyKey     string      `json:"idempotency_key"`
	RequestFingerprint string      `json:"request_fingerprint"`
}

func (q *Queries) CreateImportTask(ctx context.Context, arg CreateImportTaskParams) (ModelImportTask, error) {
	row := q.db.QueryRow(ctx, createImportTask,
		arg.TenantID,
		arg.ID,
		arg.ModelID,
		arg.Column4,
		arg.TaskType,
		arg.Source,
		arg.RepoID,
		arg.Revision,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
	)
	var i ModelImportTask
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.ModelVersionID,
		&i.TaskType,
		&i.Source,
		&i.RepoID,
		&i.Revision,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.ProgressPct,
		&i.LeaseOwner,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.RequestFingerprint,
	)
	return i, err
}

const createModel = `-- name: CreateModel :one
INSERT INTO public.models (tenant_id, id, model_id, name, display_name, description, source, capabilities, status, idempotency_key, request_fingerprint)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, $10)
RETURNING tenant_id, id, name, display_name, description, source, source_repo_id, capabilities, status, error_message, total_size_bytes, created_at, updated_at, deleted_at, idempotency_key, request_fingerprint, model_id
`

type CreateModelParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	ID                 pgtype.UUID `json:"id"`
	ModelID            string      `json:"model_id"`
	Name               string      `json:"name"`
	DisplayName        string      `json:"display_name"`
	Description        string      `json:"description"`
	Source             string      `json:"source"`
	Capabilities       []byte      `json:"capabilities"`
	IdempotencyKey     string      `json:"idempotency_key"`
	RequestFingerprint string      `json:"request_fingerprint"`
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (Model, error) {
	row := q.db.QueryRow(ctx, createModel,
		arg.TenantID,
		arg.ID,
		arg.ModelID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.Source,
		arg.Capabilities,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
	)
	var i Model
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Source,
		&i.SourceRepoID,
		&i.Capabilities,
		&i.Status,
		&i.ErrorMessage,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
	)
	return i, err
}

const createModelArtifact = `-- name: CreateModelArtifact :one
INSERT INTO public.model_artifacts
 (tenant_id, id, model_version_id, provider, reference, format, size_bytes,
  sha256, is_encrypted, encrypt_algo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING tenant_id, id, model_version_id, provider, reference, format, size_bytes, sha256, is_encrypted, encrypt_algo, created_at
`

type CreateModelArtifactParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ID             pgtype.UUID `json:"id"`
	ModelVersionID pgtype.UUID `json:"model_version_id"`
	Provider       string      `json:"provider"`
	Reference      string      `json:"reference"`
	Format         string      `json:"format"`
	SizeBytes      int64       `json:"size_bytes"`
	Sha256         string      `json:"sha256"`
	IsEncrypted    bool        `json:"is_encrypted"`
	EncryptAlgo    string      `json:"encrypt_algo"`
}

func (q *Queries) CreateModelArtifact(ctx context.Context, arg CreateModelArtifactParams) (ModelArtifact, error) {
	row := q.db.QueryRow(ctx, createModelArtifact,
		arg.TenantID,
		arg.ID,
		arg.ModelVersionID,
		arg.Provider,
		arg.Reference,
		arg.Format,
		arg.SizeBytes,
		arg.Sha256,
		arg.IsEncrypted,
		arg.EncryptAlgo,
	)
	var i ModelArtifact
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelVersionID,
		&i.Provider,
		&i.Reference,
		&i.Format,
		&i.SizeBytes,
		&i.Sha256,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.CreatedAt,
	)
	return i, err
}

const createModelVersion = `-- name: CreateModelVersion :one
WITH parent AS (
 SELECT m.id FROM public.models m
 WHERE m.tenant_id = $1 AND m.id = $15 AND m.status <> 'deleted'
 FOR KEY SHARE
)
INSERT INTO public.model_versions
 (tenant_id, id, model_id, version, format, status, is_encrypted, encrypt_algo,
  encrypt_hint, size_bytes, checksum_sha256, engine_type, startup_command, startup_args, idempotency_key, request_fingerprint)
SELECT $1, $2, parent.id, $3, $4, 'pending',
       $5, $6, $7, $8,
       $9, $10, $11, $12,
       $13, $14 FROM parent
RETURNING tenant_id, id, model_id, version, format, status, is_encrypted, encrypt_algo, encrypt_hint, size_bytes, checksum_sha256, engine_type, startup_command, startup_args, error_message, created_at, updated_at, idempotency_key, request_fingerprint
`

type CreateModelVersionParams struct {
	TenantID           pgtype.UUID `json:"tenant_id"`
	ID                 pgtype.UUID `json:"id"`
	Version            string      `json:"version"`
	Format             string      `json:"format"`
	IsEncrypted        bool        `json:"is_encrypted"`
	EncryptAlgo        string      `json:"encrypt_algo"`
	EncryptHint        string      `json:"encrypt_hint"`
	SizeBytes          int64       `json:"size_bytes"`
	ChecksumSha256     string      `json:"checksum_sha256"`
	EngineType         string      `json:"engine_type"`
	StartupCommand     string      `json:"startup_command"`
	StartupArgs        []byte      `json:"startup_args"`
	IdempotencyKey     string      `json:"idempotency_key"`
	RequestFingerprint string      `json:"request_fingerprint"`
	ModelID            pgtype.UUID `json:"model_id"`
}

func (q *Queries) CreateModelVersion(ctx context.Context, arg CreateModelVersionParams) (ModelVersion, error) {
	row := q.db.QueryRow(ctx, createModelVersion,
		arg.TenantID,
		arg.ID,
		arg.Version,
		arg.Format,
		arg.IsEncrypted,
		arg.EncryptAlgo,
		arg.EncryptHint,
		arg.SizeBytes,
		arg.ChecksumSha256,
		arg.EngineType,
		arg.StartupCommand,
		arg.StartupArgs,
		arg.IdempotencyKey,
		arg.RequestFingerprint,
		arg.ModelID,
	)
	var i ModelVersion
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Version,
		&i.Format,
		&i.Status,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.EncryptHint,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.EngineType,
		&i.StartupCommand,
		&i.StartupArgs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
	)
	return i, err
}

const failImportTask = `-- name: FailImportTask :execrows
UPDATE public.model_import_tasks
SET status = 'failed', lease_owner = '', lease_until = NULL,
    error_message = $5, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status = 'importing'
  AND lease_owner = $3 AND lease_epoch = $4 AND lease_until > clock_timestamp()
`

type FailImportTaskParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ID           pgtype.UUID `json:"id"`
	LeaseOwner   string      `json:"lease_owner"`
	LeaseEpoch   int64       `json:"lease_epoch"`
	ErrorMessage string      `json:"error_message"`
}

func (q *Queries) FailImportTask(ctx context.Context, arg FailImportTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, failImportTask,
		arg.TenantID,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseEpoch,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getImportTask = `-- name: GetImportTask :one
SELECT tenant_id, id, model_id, model_version_id, task_type, source, repo_id,
       revision, idempotency_key, request_fingerprint, status, attempt_count,
       progress_pct, lease_owner, lease_epoch, lease_until, next_attempt_at,
       error_message, created_at, updated_at, completed_at
FROM public.model_import_tasks
WHERE tenant_id = $1 AND id = $2
`

type GetImportTaskParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetImportTaskRow struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            pgtype.UUID        `json:"model_id"`
	ModelVersionID     pgtype.UUID        `json:"model_version_id"`
	TaskType           string             `json:"task_type"`
	Source             string             `json:"source"`
	RepoID             string             `json:"repo_id"`
	Revision           string             `json:"revision"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	Status             string             `json:"status"`
	AttemptCount       int32              `json:"attempt_count"`
	ProgressPct        int32              `json:"progress_pct"`
	LeaseOwner         string             `json:"lease_owner"`
	LeaseEpoch         int64              `json:"lease_epoch"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetImportTask(ctx context.Context, arg GetImportTaskParams) (GetImportTaskRow, error) {
	row := q.db.QueryRow(ctx, getImportTask, arg.TenantID, arg.ID)
	var i GetImportTaskRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.ModelVersionID,
		&i.TaskType,
		&i.Source,
		&i.RepoID,
		&i.Revision,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Status,
		&i.AttemptCount,
		&i.ProgressPct,
		&i.LeaseOwner,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getImportTaskByIdempotency = `-- name: GetImportTaskByIdempotency :one
SELECT tenant_id, id, model_id, model_version_id, task_type, source, repo_id,
       revision, idempotency_key, request_fingerprint, status, attempt_count,
       progress_pct, lease_owner, lease_epoch, lease_until, next_attempt_at,
       error_message, created_at, updated_at, completed_at
FROM public.model_import_tasks
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetImportTaskByIdempotencyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type GetImportTaskByIdempotencyRow struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            pgtype.UUID        `json:"model_id"`
	ModelVersionID     pgtype.UUID        `json:"model_version_id"`
	TaskType           string             `json:"task_type"`
	Source             string             `json:"source"`
	RepoID             string             `json:"repo_id"`
	Revision           string             `json:"revision"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	Status             string             `json:"status"`
	AttemptCount       int32              `json:"attempt_count"`
	ProgressPct        int32              `json:"progress_pct"`
	LeaseOwner         string             `json:"lease_owner"`
	LeaseEpoch         int64              `json:"lease_epoch"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetImportTaskByIdempotency(ctx context.Context, arg GetImportTaskByIdempotencyParams) (GetImportTaskByIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getImportTaskByIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i GetImportTaskByIdempotencyRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.ModelVersionID,
		&i.TaskType,
		&i.Source,
		&i.RepoID,
		&i.Revision,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Status,
		&i.AttemptCount,
		&i.ProgressPct,
		&i.LeaseOwner,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getModel = `-- name: GetModel :one
SELECT tenant_id, id, model_id, name, display_name, description, source, source_repo_id,
       capabilities, status, error_message, total_size_bytes, created_at, updated_at,
       idempotency_key, request_fingerprint
FROM public.models WHERE tenant_id = $1 AND id = $2 AND status <> 'deleted'
`

type GetModelParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetModelRow struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            string             `json:"model_id"`
	Name               string             `json:"name"`
	DisplayName        string             `json:"display_name"`
	Description        string             `json:"description"`
	Source             string             `json:"source"`
	SourceRepoID       string             `json:"source_repo_id"`
	Capabilities       []byte             `json:"capabilities"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	TotalSizeBytes     int64              `json:"total_size_bytes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
}

func (q *Queries) GetModel(ctx context.Context, arg GetModelParams) (GetModelRow, error) {
	row := q.db.QueryRow(ctx, getModel, arg.TenantID, arg.ID)
	var i GetModelRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Source,
		&i.SourceRepoID,
		&i.Capabilities,
		&i.Status,
		&i.ErrorMessage,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
	)
	return i, err
}

const getModelArtifact = `-- name: GetModelArtifact :one
SELECT tenant_id, id, model_version_id, provider, reference, format, size_bytes,
       sha256, is_encrypted, encrypt_algo, created_at
FROM public.model_artifacts
WHERE tenant_id = $1 AND model_version_id = $2
`

type GetModelArtifactParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ModelVersionID pgtype.UUID `json:"model_version_id"`
}

func (q *Queries) GetModelArtifact(ctx context.Context, arg GetModelArtifactParams) (ModelArtifact, error) {
	row := q.db.QueryRow(ctx, getModelArtifact, arg.TenantID, arg.ModelVersionID)
	var i ModelArtifact
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelVersionID,
		&i.Provider,
		&i.Reference,
		&i.Format,
		&i.SizeBytes,
		&i.Sha256,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.CreatedAt,
	)
	return i, err
}

const getModelByExternalID = `-- name: GetModelByExternalID :one
SELECT tenant_id, id, model_id, name, display_name, description, source, source_repo_id,
       capabilities, status, error_message, total_size_bytes, created_at, updated_at,
       idempotency_key, request_fingerprint
FROM public.models
WHERE tenant_id = $1 AND model_id = $2 AND status <> 'deleted'
`

type GetModelByExternalIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ModelID  string      `json:"model_id"`
}

type GetModelByExternalIDRow struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            string             `json:"model_id"`
	Name               string             `json:"name"`
	DisplayName        string             `json:"display_name"`
	Description        string             `json:"description"`
	Source             string             `json:"source"`
	SourceRepoID       string             `json:"source_repo_id"`
	Capabilities       []byte             `json:"capabilities"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	TotalSizeBytes     int64              `json:"total_size_bytes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
}

func (q *Queries) GetModelByExternalID(ctx context.Context, arg GetModelByExternalIDParams) (GetModelByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getModelByExternalID, arg.TenantID, arg.ModelID)
	var i GetModelByExternalIDRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Source,
		&i.SourceRepoID,
		&i.Capabilities,
		&i.Status,
		&i.ErrorMessage,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
	)
	return i, err
}

const getModelByIdempotency = `-- name: GetModelByIdempotency :one
SELECT tenant_id, id, name, display_name, description, source, source_repo_id, capabilities, status, error_message, total_size_bytes, created_at, updated_at, deleted_at, idempotency_key, request_fingerprint, model_id FROM public.models WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetModelByIdempotencyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetModelByIdempotency(ctx context.Context, arg GetModelByIdempotencyParams) (Model, error) {
	row := q.db.QueryRow(ctx, getModelByIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i Model
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.Source,
		&i.SourceRepoID,
		&i.Capabilities,
		&i.Status,
		&i.ErrorMessage,
		&i.TotalSizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.ModelID,
	)
	return i, err
}

const getModelVersion = `-- name: GetModelVersion :one
SELECT v.tenant_id, v.id, v.model_id, v.version, v.format, v.status,
       v.is_encrypted, v.encrypt_algo, v.encrypt_hint, v.size_bytes,
       v.checksum_sha256, v.engine_type, v.startup_command, v.startup_args,
       v.error_message, v.created_at, v.updated_at,
       m.model_id AS external_model_id,
       a.provider AS artifact_provider, a.reference AS artifact_reference,
       a.sha256 AS artifact_sha256, a.size_bytes AS artifact_size_bytes
FROM public.model_versions v
JOIN public.models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
LEFT JOIN public.model_artifacts a ON a.tenant_id = v.tenant_id AND a.model_version_id = v.id
WHERE v.tenant_id = $1 AND v.id = $2
`

type GetModelVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetModelVersionRow struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ID                pgtype.UUID        `json:"id"`
	ModelID           pgtype.UUID        `json:"model_id"`
	Version           string             `json:"version"`
	Format            string             `json:"format"`
	Status            string             `json:"status"`
	IsEncrypted       bool               `json:"is_encrypted"`
	EncryptAlgo       string             `json:"encrypt_algo"`
	EncryptHint       string             `json:"encrypt_hint"`
	SizeBytes         int64              `json:"size_bytes"`
	ChecksumSha256    string             `json:"checksum_sha256"`
	EngineType        string             `json:"engine_type"`
	StartupCommand    string             `json:"startup_command"`
	StartupArgs       []byte             `json:"startup_args"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExternalModelID   string             `json:"external_model_id"`
	ArtifactProvider  pgtype.Text        `json:"artifact_provider"`
	ArtifactReference pgtype.Text        `json:"artifact_reference"`
	ArtifactSha256    pgtype.Text        `json:"artifact_sha256"`
	ArtifactSizeBytes pgtype.Int8        `json:"artifact_size_bytes"`
}

func (q *Queries) GetModelVersion(ctx context.Context, arg GetModelVersionParams) (GetModelVersionRow, error) {
	row := q.db.QueryRow(ctx, getModelVersion, arg.TenantID, arg.ID)
	var i GetModelVersionRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Version,
		&i.Format,
		&i.Status,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.EncryptHint,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.EngineType,
		&i.StartupCommand,
		&i.StartupArgs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalModelID,
		&i.ArtifactProvider,
		&i.ArtifactReference,
		&i.ArtifactSha256,
		&i.ArtifactSizeBytes,
	)
	return i, err
}

const getModelVersionByIdempotency = `-- name: GetModelVersionByIdempotency :one
SELECT tenant_id, id, model_id, version, format, status, is_encrypted, encrypt_algo, encrypt_hint, size_bytes, checksum_sha256, engine_type, startup_command, startup_args, error_message, created_at, updated_at, idempotency_key, request_fingerprint FROM public.model_versions WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetModelVersionByIdempotencyParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) GetModelVersionByIdempotency(ctx context.Context, arg GetModelVersionByIdempotencyParams) (ModelVersion, error) {
	row := q.db.QueryRow(ctx, getModelVersionByIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i ModelVersion
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Version,
		&i.Format,
		&i.Status,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.EncryptHint,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.EngineType,
		&i.StartupCommand,
		&i.StartupArgs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
	)
	return i, err
}

const getModelVersionForImport = `-- name: GetModelVersionForImport :one
SELECT id
FROM public.model_versions
WHERE tenant_id = $1 AND model_id = $2 AND version = $3
  AND status IN ('pending', 'importing', 'error')
`

type GetModelVersionForImportParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ModelID  pgtype.UUID `json:"model_id"`
	Version  string      `json:"version"`
}

func (q *Queries) GetModelVersionForImport(ctx context.Context, arg GetModelVersionForImportParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getModelVersionForImport, arg.TenantID, arg.ModelID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getReadyModelVersion = `-- name: GetReadyModelVersion :one
SELECT v.tenant_id, v.id, v.model_id, v.version, v.format, v.status,
       v.is_encrypted, v.encrypt_algo, v.encrypt_hint, v.size_bytes,
       v.checksum_sha256, v.engine_type, v.startup_command, v.startup_args,
       v.error_message, v.created_at, v.updated_at,
       m.model_id AS external_model_id,
       a.provider AS artifact_provider, a.reference AS artifact_reference,
       a.sha256 AS artifact_sha256, a.size_bytes AS artifact_size_bytes
FROM public.model_versions v
JOIN public.models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN public.model_artifacts a ON a.tenant_id = v.tenant_id AND a.model_version_id = v.id
WHERE v.tenant_id = $1 AND v.id = $2 AND m.status <> 'deleted' AND v.status = 'ready'
  AND a.sha256 <> ''
FOR SHARE OF m, v
`

type GetReadyModelVersionParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type GetReadyModelVersionRow struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ID                pgtype.UUID        `json:"id"`
	ModelID           pgtype.UUID        `json:"model_id"`
	Version           string             `json:"version"`
	Format            string             `json:"format"`
	Status            string             `json:"status"`
	IsEncrypted       bool               `json:"is_encrypted"`
	EncryptAlgo       string             `json:"encrypt_algo"`
	EncryptHint       string             `json:"encrypt_hint"`
	SizeBytes         int64              `json:"size_bytes"`
	ChecksumSha256    string             `json:"checksum_sha256"`
	EngineType        string             `json:"engine_type"`
	StartupCommand    string             `json:"startup_command"`
	StartupArgs       []byte             `json:"startup_args"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExternalModelID   string             `json:"external_model_id"`
	ArtifactProvider  string             `json:"artifact_provider"`
	ArtifactReference string             `json:"artifact_reference"`
	ArtifactSha256    string             `json:"artifact_sha256"`
	ArtifactSizeBytes int64              `json:"artifact_size_bytes"`
}

func (q *Queries) GetReadyModelVersion(ctx context.Context, arg GetReadyModelVersionParams) (GetReadyModelVersionRow, error) {
	row := q.db.QueryRow(ctx, getReadyModelVersion, arg.TenantID, arg.ID)
	var i GetReadyModelVersionRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Version,
		&i.Format,
		&i.Status,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.EncryptHint,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.EngineType,
		&i.StartupCommand,
		&i.StartupArgs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalModelID,
		&i.ArtifactProvider,
		&i.ArtifactReference,
		&i.ArtifactSha256,
		&i.ArtifactSizeBytes,
	)
	return i, err
}

const getReadyModelVersionByExternalRef = `-- name: GetReadyModelVersionByExternalRef :one
SELECT v.tenant_id, v.id, v.model_id, v.version, v.format, v.status,
       v.is_encrypted, v.encrypt_algo, v.encrypt_hint, v.size_bytes,
       v.checksum_sha256, v.engine_type, v.startup_command, v.startup_args,
       v.error_message, v.created_at, v.updated_at,
       m.model_id AS external_model_id,
       a.provider AS artifact_provider, a.reference AS artifact_reference,
       a.sha256 AS artifact_sha256, a.size_bytes AS artifact_size_bytes
FROM public.model_versions v
JOIN public.models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
JOIN public.model_artifacts a ON a.tenant_id = v.tenant_id AND a.model_version_id = v.id
WHERE v.tenant_id = $1 AND m.model_id = $2 AND v.version = $3
  AND m.status <> 'deleted' AND v.status = 'ready' AND a.sha256 <> ''
FOR SHARE OF m, v
`

type GetReadyModelVersionByExternalRefParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ModelID  string      `json:"model_id"`
	Version  string      `json:"version"`
}

type GetReadyModelVersionByExternalRefRow struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ID                pgtype.UUID        `json:"id"`
	ModelID           pgtype.UUID        `json:"model_id"`
	Version           string             `json:"version"`
	Format            string             `json:"format"`
	Status            string             `json:"status"`
	IsEncrypted       bool               `json:"is_encrypted"`
	EncryptAlgo       string             `json:"encrypt_algo"`
	EncryptHint       string             `json:"encrypt_hint"`
	SizeBytes         int64              `json:"size_bytes"`
	ChecksumSha256    string             `json:"checksum_sha256"`
	EngineType        string             `json:"engine_type"`
	StartupCommand    string             `json:"startup_command"`
	StartupArgs       []byte             `json:"startup_args"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExternalModelID   string             `json:"external_model_id"`
	ArtifactProvider  string             `json:"artifact_provider"`
	ArtifactReference string             `json:"artifact_reference"`
	ArtifactSha256    string             `json:"artifact_sha256"`
	ArtifactSizeBytes int64              `json:"artifact_size_bytes"`
}

func (q *Queries) GetReadyModelVersionByExternalRef(ctx context.Context, arg GetReadyModelVersionByExternalRefParams) (GetReadyModelVersionByExternalRefRow, error) {
	row := q.db.QueryRow(ctx, getReadyModelVersionByExternalRef, arg.TenantID, arg.ModelID, arg.Version)
	var i GetReadyModelVersionByExternalRefRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.Version,
		&i.Format,
		&i.Status,
		&i.IsEncrypted,
		&i.EncryptAlgo,
		&i.EncryptHint,
		&i.SizeBytes,
		&i.ChecksumSha256,
		&i.EngineType,
		&i.StartupCommand,
		&i.StartupArgs,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalModelID,
		&i.ArtifactProvider,
		&i.ArtifactReference,
		&i.ArtifactSha256,
		&i.ArtifactSizeBytes,
	)
	return i, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO public.audit_events
 (tenant_id, id, actor, workload, request_id, task_id, action,
  before_state, after_state, error_class)
VALUES ($1, $2, $3, $4, $5, NULLIF($6, '00000000-0000-0000-0000-000000000000')::uuid,
        $7, $8, $9, $10)
`

type InsertAuditEventParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
	Actor       string      `json:"actor"`
	Workload    string      `json:"workload"`
	RequestID   string      `json:"request_id"`
	Column6     interface{} `json:"column_6"`
	Action      string      `json:"action"`
	BeforeState string      `json:"before_state"`
	AfterState  string      `json:"after_state"`
	ErrorClass  string      `json:"error_class"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.TenantID,
		arg.ID,
		arg.Actor,
		arg.Workload,
		arg.RequestID,
		arg.Column6,
		arg.Action,
		arg.BeforeState,
		arg.AfterState,
		arg.ErrorClass,
	)
	return err
}

const latestModelVersions = `-- name: LatestModelVersions :many
SELECT DISTINCT ON (v.model_id)
       v.tenant_id, v.id, v.model_id, v.version, v.format, v.status, v.is_encrypted, v.encrypt_algo,
       v.encrypt_hint, v.size_bytes, v.checksum_sha256, v.engine_type, v.startup_command,
       v.startup_args, v.error_message, v.created_at, v.updated_at,
       m.model_id AS external_model_id,
       COALESCE(a.provider, '')::text AS artifact_provider,
       COALESCE(a.reference, '')::text AS artifact_reference
FROM public.model_versions v
JOIN public.models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
LEFT JOIN public.model_artifacts a ON a.tenant_id = v.tenant_id AND a.model_version_id = v.id
WHERE v.tenant_id = $1 AND v.model_id = ANY($2::uuid[]) AND v.status <> 'deleted' AND m.status <> 'deleted'
ORDER BY v.model_id, v.created_at DESC, v.id DESC
`

type LatestModelVersionsParams struct {
	TenantID pgtype.UUID   `json:"tenant_id"`
	Column2  []pgtype.UUID `json:"column_2"`
}

type LatestModelVersionsRow struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ID                pgtype.UUID        `json:"id"`
	ModelID           pgtype.UUID        `json:"model_id"`
	Version           string             `json:"version"`
	Format            string             `json:"format"`
	Status            string             `json:"status"`
	IsEncrypted       bool               `json:"is_encrypted"`
	EncryptAlgo       string             `json:"encrypt_algo"`
	EncryptHint       string             `json:"encrypt_hint"`
	SizeBytes         int64              `json:"size_bytes"`
	ChecksumSha256    string             `json:"checksum_sha256"`
	EngineType        string             `json:"engine_type"`
	StartupCommand    string             `json:"startup_command"`
	StartupArgs       []byte             `json:"startup_args"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExternalModelID   string             `json:"external_model_id"`
	ArtifactProvider  string             `json:"artifact_provider"`
	ArtifactReference string             `json:"artifact_reference"`
}

func (q *Queries) LatestModelVersions(ctx context.Context, arg LatestModelVersionsParams) ([]LatestModelVersionsRow, error) {
	rows, err := q.db.Query(ctx, latestModelVersions, arg.TenantID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestModelVersionsRow{}
	for rows.Next() {
		var i LatestModelVersionsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ModelID,
			&i.Version,
			&i.Format,
			&i.Status,
			&i.IsEncrypted,
			&i.EncryptAlgo,
			&i.EncryptHint,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.EngineType,
			&i.StartupCommand,
			&i.StartupArgs,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalModelID,
			&i.ArtifactProvider,
			&i.ArtifactReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueImportTasks = `-- name: ListDueImportTasks :many
SELECT tenant_id, id, model_id, model_version_id, task_type, source, repo_id,
       revision, idempotency_key, status, attempt_count, progress_pct,
       lease_owner, lease_epoch, lease_until, next_attempt_at, error_message,
       created_at, updated_at, completed_at
FROM public.model_import_tasks
WHERE ($1::uuid IS NULL OR tenant_id = $1)
  AND status IN ('pending','importing')
  AND next_attempt_at <= clock_timestamp()
  AND (lease_until IS NULL OR lease_until <= clock_timestamp())
ORDER BY next_attempt_at, created_at, id
LIMIT $2
`

type ListDueImportTasksParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
}

type ListDueImportTasksRow struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ID             pgtype.UUID        `json:"id"`
	ModelID        pgtype.UUID        `json:"model_id"`
	ModelVersionID pgtype.UUID        `json:"model_version_id"`
	TaskType       string             `json:"task_type"`
	Source         string             `json:"source"`
	RepoID         string             `json:"repo_id"`
	Revision       string             `json:"revision"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	ProgressPct    int32              `json:"progress_pct"`
	LeaseOwner     string             `json:"lease_owner"`
	LeaseEpoch     int64              `json:"lease_epoch"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorMessage   string             `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListDueImportTasks(ctx context.Context, arg ListDueImportTasksParams) ([]ListDueImportTasksRow, error) {
	rows, err := q.db.Query(ctx, listDueImportTasks, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueImportTasksRow{}
	for rows.Next() {
		var i ListDueImportTasksRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ModelID,
			&i.ModelVersionID,
			&i.TaskType,
			&i.Source,
			&i.RepoID,
			&i.Revision,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.ProgressPct,
			&i.LeaseOwner,
			&i.LeaseEpoch,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueImportTasksAll = `-- name: ListDueImportTasksAll :many
SELECT tenant_id, id, model_id, model_version_id, task_type, source, repo_id,
       revision, idempotency_key, status, attempt_count, progress_pct,
       lease_owner, lease_epoch, lease_until, next_attempt_at, error_message,
       created_at, updated_at, completed_at
FROM public.model_import_tasks
WHERE status IN ('pending','importing')
  AND next_attempt_at <= clock_timestamp()
  AND (lease_until IS NULL OR lease_until <= clock_timestamp())
ORDER BY next_attempt_at, created_at, id
LIMIT $1
`

type ListDueImportTasksAllRow struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ID             pgtype.UUID        `json:"id"`
	ModelID        pgtype.UUID        `json:"model_id"`
	ModelVersionID pgtype.UUID        `json:"model_version_id"`
	TaskType       string             `json:"task_type"`
	Source         string             `json:"source"`
	RepoID         string             `json:"repo_id"`
	Revision       string             `json:"revision"`
	IdempotencyKey string             `json:"idempotency_key"`
	Status         string             `json:"status"`
	AttemptCount   int32              `json:"attempt_count"`
	ProgressPct    int32              `json:"progress_pct"`
	LeaseOwner     string             `json:"lease_owner"`
	LeaseEpoch     int64              `json:"lease_epoch"`
	LeaseUntil     pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt  pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorMessage   string             `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) ListDueImportTasksAll(ctx context.Context, limit int32) ([]ListDueImportTasksAllRow, error) {
	rows, err := q.db.Query(ctx, listDueImportTasksAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueImportTasksAllRow{}
	for rows.Next() {
		var i ListDueImportTasksAllRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ModelID,
			&i.ModelVersionID,
			&i.TaskType,
			&i.Source,
			&i.RepoID,
			&i.Revision,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.ProgressPct,
			&i.LeaseOwner,
			&i.LeaseEpoch,
			&i.LeaseUntil,
			&i.NextAttemptAt,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelVersions = `-- name: ListModelVersions :many
SELECT v.tenant_id, v.id, v.model_id, v.version, v.format, v.status, v.is_encrypted, v.encrypt_algo,
       v.encrypt_hint, v.size_bytes, v.checksum_sha256, v.engine_type, v.startup_command,
       v.startup_args, v.error_message, v.created_at, v.updated_at,
       m.model_id AS external_model_id,
       COALESCE(a.provider, '')::text AS artifact_provider,
       COALESCE(a.reference, '')::text AS artifact_reference
FROM public.model_versions v
JOIN public.models m ON m.tenant_id = v.tenant_id AND m.id = v.model_id
LEFT JOIN public.model_artifacts a ON a.tenant_id = v.tenant_id AND a.model_version_id = v.id
WHERE v.tenant_id = $1 AND v.model_id = $2 AND v.status <> 'deleted' AND m.status <> 'deleted'
  AND ($3::timestamptz IS NULL
       OR (v.created_at, v.id) < ($3::timestamptz, $4::uuid))
ORDER BY v.created_at DESC, v.id DESC
LIMIT $5
`

type ListModelVersionsParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ModelID         pgtype.UUID        `json:"model_id"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListModelVersionsRow struct {
	TenantID          pgtype.UUID        `json:"tenant_id"`
	ID                pgtype.UUID        `json:"id"`
	ModelID           pgtype.UUID        `json:"model_id"`
	Version           string             `json:"version"`
	Format            string             `json:"format"`
	Status            string             `json:"status"`
	IsEncrypted       bool               `json:"is_encrypted"`
	EncryptAlgo       string             `json:"encrypt_algo"`
	EncryptHint       string             `json:"encrypt_hint"`
	SizeBytes         int64              `json:"size_bytes"`
	ChecksumSha256    string             `json:"checksum_sha256"`
	EngineType        string             `json:"engine_type"`
	StartupCommand    string             `json:"startup_command"`
	StartupArgs       []byte             `json:"startup_args"`
	ErrorMessage      string             `json:"error_message"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExternalModelID   string             `json:"external_model_id"`
	ArtifactProvider  string             `json:"artifact_provider"`
	ArtifactReference string             `json:"artifact_reference"`
}

func (q *Queries) ListModelVersions(ctx context.Context, arg ListModelVersionsParams) ([]ListModelVersionsRow, error) {
	rows, err := q.db.Query(ctx, listModelVersions,
		arg.TenantID,
		arg.ModelID,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelVersionsRow{}
	for rows.Next() {
		var i ListModelVersionsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ModelID,
			&i.Version,
			&i.Format,
			&i.Status,
			&i.IsEncrypted,
			&i.EncryptAlgo,
			&i.EncryptHint,
			&i.SizeBytes,
			&i.ChecksumSha256,
			&i.EngineType,
			&i.StartupCommand,
			&i.StartupArgs,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalModelID,
			&i.ArtifactProvider,
			&i.ArtifactReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
SELECT tenant_id, id, model_id, name, display_name, description, source, source_repo_id,
       capabilities, status, error_message, total_size_bytes, created_at, updated_at,
       idempotency_key, request_fingerprint
FROM public.models
WHERE tenant_id = $1 AND status <> 'deleted'
  AND ($2::text = '' OR status = $2)
  AND ($3::text = '' OR source = $3)
  AND ($4::text = '' OR capabilities ? $4::text)
  AND ($5::text = ''
       OR strpos(lower(name), lower($5)) > 0
       OR strpos(lower(display_name), lower($5)) > 0
       OR strpos(lower(model_id), lower($5)) > 0)
  AND ($6::timestamptz IS NULL
       OR (created_at, id) < ($6::timestamptz, $7::uuid))
ORDER BY created_at DESC, id DESC
LIMIT $8
`

type ListModelsParams struct {
	TenantID        pgtype.UUID        `json:"tenant_id"`
	StatusFilter    string             `json:"status_filter"`
	SourceFilter    string             `json:"source_filter"`
	Capability      string             `json:"capability"`
	Keyword         string             `json:"keyword"`
	BeforeCreatedAt pgtype.Timestamptz `json:"before_created_at"`
	BeforeID        pgtype.UUID        `json:"before_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListModelsRow struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            string             `json:"model_id"`
	Name               string             `json:"name"`
	DisplayName        string             `json:"display_name"`
	Description        string             `json:"description"`
	Source             string             `json:"source"`
	SourceRepoID       string             `json:"source_repo_id"`
	Capabilities       []byte             `json:"capabilities"`
	Status             string             `json:"status"`
	ErrorMessage       string             `json:"error_message"`
	TotalSizeBytes     int64              `json:"total_size_bytes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]ListModelsRow, error) {
	rows, err := q.db.Query(ctx, listModels,
		arg.TenantID,
		arg.StatusFilter,
		arg.SourceFilter,
		arg.Capability,
		arg.Keyword,
		arg.BeforeCreatedAt,
		arg.BeforeID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModelsRow{}
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ID,
			&i.ModelID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.Source,
			&i.SourceRepoID,
			&i.Capabilities,
			&i.Status,
			&i.ErrorMessage,
			&i.TotalSizeBytes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IdempotencyKey,
			&i.RequestFingerprint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markModelVersionError = `-- name: MarkModelVersionError :execrows
UPDATE public.model_versions
SET status = 'error', error_message = $3, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status IN ('pending', 'importing')
`

type MarkModelVersionErrorParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ID           pgtype.UUID `json:"id"`
	ErrorMessage string      `json:"error_message"`
}

func (q *Queries) MarkModelVersionError(ctx context.Context, arg MarkModelVersionErrorParams) (int64, error) {
	result, err := q.db.Exec(ctx, markModelVersionError, arg.TenantID, arg.ID, arg.ErrorMessage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markModelVersionReady = `-- name: MarkModelVersionReady :execrows
UPDATE public.model_versions v
SET status = 'ready', updated_at = clock_timestamp(), error_message = ''
WHERE v.tenant_id = $1 AND v.id = $2 AND v.status IN ('pending', 'importing')
  AND EXISTS (
    SELECT 1 FROM public.model_artifacts a
    WHERE a.tenant_id = v.tenant_id
      AND a.model_version_id = v.id
      AND a.reference <> ''
      AND a.sha256 = v.checksum_sha256
      AND a.sha256 <> ''
  )
`

type MarkModelVersionReadyParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) MarkModelVersionReady(ctx context.Context, arg MarkModelVersionReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markModelVersionReady, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewImportTaskLease = `-- name: RenewImportTaskLease :execrows
UPDATE public.model_import_tasks
SET lease_until = clock_timestamp() + ($5::bigint * interval '1 microsecond'),
    updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status = 'importing'
  AND lease_owner = $3 AND lease_epoch = $4 AND lease_until > clock_timestamp()
`

type RenewImportTaskLeaseParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	ID         pgtype.UUID `json:"id"`
	LeaseOwner string      `json:"lease_owner"`
	LeaseEpoch int64       `json:"lease_epoch"`
	Column5    int64       `json:"column_5"`
}

func (q *Queries) RenewImportTaskLease(ctx context.Context, arg RenewImportTaskLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewImportTaskLease,
		arg.TenantID,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseEpoch,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryFailedImportTask = `-- name: RetryFailedImportTask :one
UPDATE public.model_import_tasks
SET status = 'pending', attempt_count = 0, progress_pct = 0,
    lease_owner = '', lease_until = NULL, next_attempt_at = clock_timestamp(),
    error_message = '', completed_at = NULL, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status = 'failed'
RETURNING tenant_id, id, model_id, model_version_id, task_type, source, repo_id,
          revision, idempotency_key, request_fingerprint, status, attempt_count,
          progress_pct, lease_owner, lease_epoch, lease_until, next_attempt_at,
          error_message, created_at, updated_at, completed_at
`

type RetryFailedImportTaskParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

type RetryFailedImportTaskRow struct {
	TenantID           pgtype.UUID        `json:"tenant_id"`
	ID                 pgtype.UUID        `json:"id"`
	ModelID            pgtype.UUID        `json:"model_id"`
	ModelVersionID     pgtype.UUID        `json:"model_version_id"`
	TaskType           string             `json:"task_type"`
	Source             string             `json:"source"`
	RepoID             string             `json:"repo_id"`
	Revision           string             `json:"revision"`
	IdempotencyKey     string             `json:"idempotency_key"`
	RequestFingerprint string             `json:"request_fingerprint"`
	Status             string             `json:"status"`
	AttemptCount       int32              `json:"attempt_count"`
	ProgressPct        int32              `json:"progress_pct"`
	LeaseOwner         string             `json:"lease_owner"`
	LeaseEpoch         int64              `json:"lease_epoch"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	NextAttemptAt      pgtype.Timestamptz `json:"next_attempt_at"`
	ErrorMessage       string             `json:"error_message"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) RetryFailedImportTask(ctx context.Context, arg RetryFailedImportTaskParams) (RetryFailedImportTaskRow, error) {
	row := q.db.QueryRow(ctx, retryFailedImportTask, arg.TenantID, arg.ID)
	var i RetryFailedImportTaskRow
	err := row.Scan(
		&i.TenantID,
		&i.ID,
		&i.ModelID,
		&i.ModelVersionID,
		&i.TaskType,
		&i.Source,
		&i.RepoID,
		&i.Revision,
		&i.IdempotencyKey,
		&i.RequestFingerprint,
		&i.Status,
		&i.AttemptCount,
		&i.ProgressPct,
		&i.LeaseOwner,
		&i.LeaseEpoch,
		&i.LeaseUntil,
		&i.NextAttemptAt,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const retryImportTask = `-- name: RetryImportTask :execrows
UPDATE public.model_import_tasks
SET status = 'pending', lease_owner = '', lease_until = NULL,
    next_attempt_at = clock_timestamp() + ($5::bigint * interval '1 microsecond'),
    error_message = $6, updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status = 'importing'
  AND lease_owner = $3 AND lease_epoch = $4 AND lease_until > clock_timestamp()
`

type RetryImportTaskParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ID           pgtype.UUID `json:"id"`
	LeaseOwner   string      `json:"lease_owner"`
	LeaseEpoch   int64       `json:"lease_epoch"`
	Column5      int64       `json:"column_5"`
	ErrorMessage string      `json:"error_message"`
}

func (q *Queries) RetryImportTask(ctx context.Context, arg RetryImportTaskParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryImportTask,
		arg.TenantID,
		arg.ID,
		arg.LeaseOwner,
		arg.LeaseEpoch,
		arg.Column5,
		arg.ErrorMessage,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setModelVersionChecksum = `-- name: SetModelVersionChecksum :execrows
UPDATE public.model_versions
SET checksum_sha256 = $3, size_bytes = CASE WHEN $4::bigint >= 0 THEN $4 ELSE size_bytes END,
    updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND (checksum_sha256 = '' OR checksum_sha256 = $3)
  AND (
    status IN ('pending', 'importing')
    OR (status = 'ready' AND checksum_sha256 = $3
        AND ($4::bigint < 0 OR size_bytes = $4))
  )
`

type SetModelVersionChecksumParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	ID             pgtype.UUID `json:"id"`
	ChecksumSha256 string      `json:"checksum_sha256"`
	Column4        int64       `json:"column_4"`
}

func (q *Queries) SetModelVersionChecksum(ctx context.Context, arg SetModelVersionChecksumParams) (int64, error) {
	result, err := q.db.Exec(ctx, setModelVersionChecksum,
		arg.TenantID,
		arg.ID,
		arg.ChecksumSha256,
		arg.Column4,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteModel = `-- name: SoftDeleteModel :execrows
UPDATE public.models
SET status = 'deleted', deleted_at = clock_timestamp(), updated_at = clock_timestamp()
WHERE tenant_id = $1 AND id = $2 AND status <> 'deleted'
`

type SoftDeleteModelParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SoftDeleteModel(ctx context.Context, arg SoftDeleteModelParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteModel, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
